library:
  source-dirs: src
  default-extensions:
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - TupleSections
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - GeneralisedNewtypeDeriving
  - StandaloneDeriving
  - BangPatterns
  - KindSignatures
  - ScopedTypeVariables
  - TypeApplications
tests:
  Minesweeper-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Minesweeper
copyright: 2019 Pierce Darragh
maintainer: pierce.darragh@gmail.com
dependencies:
- random-shuffle
- MonadRandom
- base >= 4.7 && < 5
name: Minesweeper
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Pierce Darragh
github: pdarragh/Minesweeper
license: BSD3
executables:
  Minesweeper-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - Minesweeper
description: Please see the README on GitHub at <https://github.com/pdarragh/Minesweeper#readme>
